#!/bin/bash

#PBS -V
#PBS -M mcala@umich.edu
#PBS -m ae
#PBS -j eo
#PBS -q fluxod
#PBS -A kioup_fluxod
#PBS -l qos=flux
#PBS -N da.52.1E17
#PBS -l walltime=03:00:00
#PBS -l nodes=1:ppn=1

#  Include the next three lines always
if [ "x${PBS_NODEFILE}" != "x" ] ; then
   cat $PBS_NODEFILE   # contains a list of the CPUs you were using
fi

cd $PBS_O_WORKDIR

cd ../

/home/mcala/scripts/direct_auger/utilities/make_run.zsh hhe

rm combinations.dat

sed -i -e 's/direct_first_run=.false./direct_first_run=.true./g' direct.in
mpirun -n 1 ~/soft/auger/bin/direct_auger_hhe.x direct.in > direct_serial.out

wc -l combinations.dat | awk '{print $1}' > combos.dat
cat combinations.dat >> combos.dat
mv combos.dat combinations.dat
cp combinations.dat combinations_hhe.dat

rm combinations.dat
/home/mcala/scripts/direct_auger/utilities/make_run.zsh eeh

sed -i -e 's/direct_first_run=.false./direct_first_run=.true./g' direct.in
mpirun -n 1 ~/soft/auger/bin/direct_auger_eeh.x direct.in > direct_serial.out

wc -l combinations.dat | awk '{print $1}' > combos.dat
cat combinations.dat >> combos.dat
mv combos.dat combinations.dat
cp combinations.dat combinations_eeh.dat
